# Generated by Django 3.2.4 on 2021-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
