# Generated by Django 3.2.4 on 2021-07-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.BooleanField(blank=True, max_length=254, null=True),
        ),
    ]
