# Generated by Django 3.2.4 on 2021-08-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customer_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_review',
        ),
    ]
