# Generated by Django 3.2.4 on 2021-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cust_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_review',
            name='name',
            field=models.CharField(default='Raspberry Pi 4 Model B', max_length=254),
            preserve_default=False,
        ),
    ]
